// src/pages/Contact.vue
<template>
  <PageWrapper class="flex flex-col justify-center" id="contact">
    <Header>Contact</Header>
    <section class="flex flex-col gap-6 pl-4 lg:flex-row lg:gap-20 lg:pl-8 [&>*]:flex-1">
      <div>
        <header class="text-secondary text-responsive-h3">Have a project in mind?</header>
        <div>My inbox is always open for new opportunities.</div>

        <div class="mt-16 hidden flex-col gap-4 lg:flex">
          <a href="https://github.com/Myphz" target="_blank" class="flex w-fit items-center gap-2">
            <img src="/icons/github.png" class="img" />
            <span>Myphz</span>
          </a>
          <a
            href="mailto:danielscanu45@outlook.it"
            target="_blank"
            class="flex w-fit items-center gap-2"
          >
            <img src="/icons/email.svg" class="img scale-[0.8]" />
            <span>danielscanu45@outlook.it</span>
          </a>
          <a
            href="https://www.linkedin.com/in/danielscanu/"
            target="_blank"
            class="flex w-fit items-center gap-2"
          >
            <img src="/icons/linkedin.png" class="img" />
            <span>Daniel Scanu</span>
          </a>
        </div>
      </div>

      <form class="flex max-w-[40rem] flex-col gap-2 lg:gap-8 lg:pr-16" @submit.prevent>
        <Input label="Email" type="email" />
        <Input label="Subject" />
        <Textarea label="Message" />
        <Button variant="primary" type="submit">Submit</Button>
      </form>

      <div class="flex flex-col gap-2 lg:hidden">
        <a href="https://github.com/Myphz" target="_blank" class="flex w-fit items-center gap-2">
          <img src="/icons/github.png" class="img" />
          <span>Myphz</span>
        </a>
        <a
          href="mailto:danielscanu45@outlook.it"
          target="_blank"
          class="flex w-fit items-center gap-2"
        >
          <img src="/icons/email.svg" class="img scale-[0.8]" />
          <span>danielscanu45@outlook.it</span>
        </a>
        <a
          href="https://www.linkedin.com/in/danielscanu/"
          target="_blank"
          class="flex w-fit items-center gap-2"
        >
          <img src="/icons/linkedin.png" class="img" />
          <span>Daniel Scanu</span>
        </a>
      </div>
    </section>
    <span class="mt-2 font-subheader text-secondary text-responsive-h2 lg:mt-8">{{ "}" }}</span>
  </PageWrapper>
</template>

<script setup lang="ts">
import PageWrapper from "@/components/PageWrapper.vue";
import Header from "@/components/Header.vue";
import Input from "@/components/Input.vue";
import Textarea from "@/components/Textarea.vue";
import Button from "@/components/Button.vue";
</script>

<style scoped>
.img {
  @apply aspect-square w-8 lg:w-12;
}
</style>

// src/pages/Contact/index.tsx
import React from "react";
import { Button } from "../../components/Button";
import { TypeText } from "../../components/TypeText";
import "./style.sass"

export const Contact: React.FC = () => {
  return (
    <main className="justify-center flex-column contact-main" id="contact">
      <h1 className="color-primary font-title block no-trail">
        <TypeText text="Contact" delay={200} speed={100} blinkDelay={50} />
      </h1>
      <section className="input-section">
        <h4 className="block no-trail">
          My inbox is always open for new opportunities.<br />
          Feel free to contact me for any inquiries you may have!<br />
          Alternatively, you can send an email to <a href="mailto:danielscanu45@outlook.it" className="a-link">danielscanu45@outlook.it</a>
        </h4>
        <form className="input-form h4">
          <div>
            <input type="text" placeholder="Email" autoComplete="email" spellCheck="false" autoCapitalize="none" />
            <span className="focus-border"></span>
          </div>
          <div>
            <input type="text" placeholder="Subject" spellCheck="false" autoCapitalize="none" />
            <span className="focus-border"></span>
          </div>

          <div>
            <textarea placeholder="Message" />
            <span className="focus-border"></span>
          </div>

          <Button submit>Send Message</Button>
        </form>
      </section>
    </main>
  );
}
