// src/components/Footer.vue
<template>
  <footer class="relative overflow-y-clip">
    <hr class="absolute left-[-10%] h-2 w-[200vw] text-secondary" />
    <hr class="absolute left-[-10%] h-2 w-[200vw] bg-secondary text-secondary blur-[20px]" />

    <section class="mt-8 flex flex-col gap-6">
      <MainText :animated="false" />
      <div>Powered by Phoexa</div>
      <a class="text-secondary underline">danielscanu45@outlook.it</a>
      <div class="flex gap-4">
        <a href="https://github.com/Myphz" target="_blank">
          <img src="/icons/github.png" alt="github" />
        </a>
        <a href="https://www.linkedin.com/in/danielscanu/" target="_blank">
          <img src="/icons/linkedin.png" alt="linkedin" />
        </a>
      </div>
    </section>
  </footer>
</template>

<script setup lang="ts">
import MainText from "./MainText.vue";
</script>

// src/components/Footer/index.tsx
import React from "react";
import { fetchIcon } from "../../utilities/fetch";
import "./style.sass";

export const Footer: React.FC = () => {
  return (
    <footer>
      <aside className="contacts-aside">
        <a href="https://github.com/Myphz" target="_blank">
          <img src={fetchIcon("github")} alt="github" />
        </a>
        <a href="https://www.linkedin.com/in/danielscanu" target="_blank">
          <img src={fetchIcon("linkedin")} alt="linkedin" />
        </a>
        <a href="mailto:danielscanu45@outlook.it" target="_blank">
          <img src={fetchIcon("email")} alt="email" />
        </a>
        <hr />
      </aside>
      <div className="scroll-text">
        <span>SCROLL <img src={fetchIcon("arrow")} alt="arrow" /></span>
      </div>
    </footer>
  );
}
